name: Build and Test
run-name: Build and test workflow
on:
  push:
  pull_request:
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run test and building
        run: gradle clean test compileJava jar
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs